import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "./providers/TanstackProvider";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen overflow-hidden bg-gradient-to-tr from-emerald-300 to-blue-300">
          {/* <Provider> */}
          <TanstackProvider>{children}</TanstackProvider>
          {/* </Provider> */}
        </div>
      </body>
    </html>
  );
}
